version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    ports:
      - "5000:5000"
    
    networks:
      - taskmaster-network
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmaster-frontend
    ports:
      - "3000:3000"
    depends_on:
    - backend

    networks:
      - taskmaster-network
    restart: unless-stopped

networks:
  taskmaster-network:
    driver: bridge
    name: taskmaster-network
